'use client';

import { Box, Container, Typography } from '@mui/material';
import CustomBreadcrumbs from 'src/components/custom-breadcrumbs';
import { alpha, useTheme } from '@mui/material/styles';
import { useSettingsContext } from 'src/components/settings';
import SharesHolderInfoTable from '../sharesholder-info/sharesholder-info';
import { bgGradient } from '../../../theme/css';

export default function SharesHolderInfoView() {
  const settings = useSettingsContext();
  const theme = useTheme();
  return (
    <Container maxWidth={settings.themeStretch ? false : 'lg'}>
      <CustomBreadcrumbs
        heading="Danh sách các cổ đông 2024"
        links={[{ name: '' }]}
        sx={{
          mb: { xs: 1, md: 1 },
        }}
      />
      <SharesHolderInfoTable
        tableData={[
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'dsdfsfsdfsdfsdfsfsdfsdfsdf',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: 'fsdfs sdfsfsdf fsfsdfsdf fsdfsdfs',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
          {
            code_shareholder: 'V317001',
            password: 'dsadjk2b23',
            name_shareholder: 'Mr.A',
            cp_holding: '430.000',
            rate: '2%',
            total_shareholder_join: '430.000',
            rate_join: '2%',
            status: 'Tham dự',
            role: 'USER',
            telegram_id: '6.873.071.176',
            note: '',
          },
        ]}
        tableLabels={[
          { id: 'stt', label: 'STT' },
          { id: 'code_shareholder', label: 'Mã cổ đông' },
          { id: 'password', label: 'Password' },
          { id: 'name_shareholder', label: 'Tên cổ đông' },
          { id: 'cp_holding', label: 'CP sỡ hữu' },
          { id: 'rate', label: 'Tỷ lệ %' },
          { id: 'total_shareholder_join', label: 'Tổng CP tham dự' },
          { id: 'rate_join', label: 'Tỷ lệ tham dự %' },
          { id: 'status', label: 'Trạng thái' },
          { id: 'role', label: 'Role' },
          { id: 'telegram_id', label: 'Telegram ID' },
          { id: 'note', label: 'Ghi chú' },
        ]}
        sx={{
          maxHeight: '40%',
          overflow: 'auto',
        }}
      />
      <Box
        sx={{
          ...bgGradient({
            direction: '135deg',
            startColor: alpha(theme.palette.primary.light, 0.2),
            endColor: alpha(theme.palette.primary.main, 0.2),
          }),
          color: '#000',
          marginTop: '10px',
          padding: '10px',
          borderRadius: '10px',
          width: '20%',
        }}
      >
        <Typography sx={{ fontWeight: 500 }}>Tổng cổ phần sữ hữu: 10</Typography>
        <Typography sx={{ fontWeight: 500 }}>Tổng cổ phần tham dự: 10</Typography>
      </Box>
    </Container>
  );
}
